package jclasschin.entity;
// Generated Jun 22, 2014 8:22:51 PM by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import jclasschin.model.CtacssManager;

/**
 * Field generated by hbm2java
 */
public class Field implements java.io.Serializable
{

    private Integer id;
    private String name;
    private Set statuses = new HashSet(0);
    private Set persons = new HashSet(0);
    private Set dedications = new HashSet(0);
    private Set courses = new HashSet(0);

    /* 1393 - 04 - 07 */
    public String majava1String = "";
    public int numberOfDedicationClass=0;

    public Field()
    {

    }

    public Field(String name)
    {
        this.name = name;

    }

    public Field(String name, Set statuses, Set persons, Set dedications, Set courses)
    {
        this.name = name;
        this.statuses = statuses;
        this.persons = persons;
        this.dedications = dedications;
        this.courses = courses;

    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public Set getStatuses()
    {
        return this.statuses;
    }

    public void setStatuses(Set statuses)
    {
        this.statuses = statuses;
    }

    public Set getPersons()
    {
        return this.persons;
    }

    public void setPersons(Set persons)
    {
        this.persons = persons;
    }

    public Set getDedications()
    {
        return this.dedications;
    }

    public void setDedications(Set dedications)
    {
        this.dedications = dedications;
    }

    public Set getCourses()
    {
        return this.courses;
    }

    public void setCourses(Set courses)
    {
        this.courses = courses;
    }

    public void initMajava()
    {
        ArrayList<Dedication> classList = new ArrayList(this.dedications);
        Collections.sort(classList, (Dedication pi1, Dedication pi2) -> pi1.getClassroom().getName().compareTo(pi2.getClassroom().getName()));

        classList.stream().forEach((c) ->
        {
            if (((Dedication) c).getTerm().getName() == null ? CtacssManager.currentTerm.getName() == null : ((Dedication) c).getTerm().getName().equals(CtacssManager.currentTerm.getName()))
            {
                majava1String += ((Dedication) c).getClassroom().getName() + " - ";
                numberOfDedicationClass++;
            }
        });
        if (majava1String.length() > 2)
        {
            majava1String = majava1String.substring(0, majava1String.length() - 3);
        }
    }

}
